// <auto-generated />
using System;
using Erm.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace erm.Migrations
{
    [DbContext(typeof(ErmDbContext))]
    [Migration("20240417064946_new5")]
    partial class new5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Erm.Models.MyTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("first");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MyTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dce2aa6e-4f6b-4c64-802a-45c1696381c1"),
                            AssignedTo = "John Doe",
                            EndDate = new DateTime(2015, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "first task",
                            StartDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Erm.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("first");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Erm.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("first");

                    b.Property<string>("Risks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sprints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fcb5110c-529e-4aea-b893-96accfbd4a5c"),
                            AssignedTo = "Scrum",
                            EndDate = new DateTime(2016, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "first Project",
                            Risks = "risks",
                            Sprints = "3",
                            StartDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Erm.Models.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Probability")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Risk");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e74bfb9c-7625-4224-80bf-7f58b2741637"),
                            Description = "descriptionInContext",
                            Impact = 1,
                            Name = "firstRiskInContext",
                            Probability = 2
                        },
                        new
                        {
                            Id = new Guid("44df0571-52a6-4405-836c-b3bf81a73b68"),
                            Description = "Description of first risk",
                            Impact = 3,
                            Name = "First Risk",
                            Probability = 2
                        },
                        new
                        {
                            Id = new Guid("e557ff39-c4a6-41f6-9cf1-700d0d9fc202"),
                            Description = "Description of second risk",
                            Impact = 2,
                            Name = "Second Risk",
                            Probability = 1
                        });
                });

            modelBuilder.Entity("Erm.Models.Worker", b =>
                {
                    b.HasBaseType("Erm.Models.Person");

                    b.Property<string>("Responsibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Worker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94fceb05-a128-4bca-bb84-89f3aabc4dac"),
                            FirstName = "first",
                            LastName = "last",
                            Password = "123",
                            RefreshToken = "refresh_token_value",
                            Role = "admin",
                            Username = "maga",
                            Responsibility = "some_responsibility"
                        },
                        new
                        {
                            Id = new Guid("ec0fe01c-64ab-455e-a3ed-d22ff3b20611"),
                            FirstName = "second",
                            LastName = "last1",
                            Password = "222",
                            RefreshToken = "refresh_token_value1",
                            Role = "editor",
                            Username = "baha",
                            Responsibility = "some_responsibility1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
