// <auto-generated />
using System;
using Erm.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace erm.Migrations
{
    [DbContext(typeof(ErmDbContext))]
    [Migration("20240415100112_new1")]
    partial class new1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("erm.Models.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Probability")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Risk");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a4db473-f697-4dd7-98ce-d99f7079d360"),
                            Description = "descriptionInContext",
                            Impact = 1,
                            Name = "firstRiskInContext",
                            Probability = 2
                        },
                        new
                        {
                            Id = new Guid("551df029-5aef-4426-a618-11e1e421e010"),
                            Description = "Description of first risk",
                            Impact = 3,
                            Name = "First Risk",
                            Probability = 2
                        },
                        new
                        {
                            Id = new Guid("93acb856-5b8b-4931-b258-c1b008ee3927"),
                            Description = "Description of second risk",
                            Impact = 2,
                            Name = "Second Risk",
                            Probability = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
