// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace erm.Migrations
{
    [DbContext(typeof(ErmDbContext))]
    partial class ErmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("erm.Models.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Probability")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Risk");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62482143-fb8b-479f-8937-d3f035458447"),
                            Description = "descriptionInContext",
                            Impact = 0,
                            Name = "firstRiskInContext",
                            Probability = 2
                        },
                        new
                        {
                            Id = new Guid("1ce50ad1-bb41-429e-a512-18ee759f87d1"),
                            Description = "Description of first risk",
                            Impact = 0,
                            Name = "First Risk",
                            Probability = 0
                        },
                        new
                        {
                            Id = new Guid("fb9ecdd1-9125-4427-9575-6248019d642a"),
                            Description = "Description of second risk",
                            Impact = 1,
                            Name = "Second Risk",
                            Probability = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
